feed/urls.py
from django.urls import path, include

from . import views

app_name = 'feed'

auth_urlpatterns = [
    path('signup', views.signup_user, name='signup'),
    path('activate/<uidb64>/<token>', views.activate_user, name='activate_user'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
]

user_urlpatterns = [
    path('<user_id>', views.user_profile, name='user_profile'),
    path('<user_id>/edit', views.user_edit_profile, name='user_edit_profile'),
    path('<user_id>/follow', views.follow, name='follow'),
    path('<user_id>/followers', views.followers, name='followers'),
    path('<user_id>/following', views.following, name='following'),
]

post_urlpatterns = [
    path('create', views.create_post, name='create_post'),
    path('<post_id>/like', views.like, name='like'),
    path('<post_id>/make_comment', views.make_comment, name='make_comment'),
]

comment_urlpatterns = [
    path('<comment_id>/like', views.like_comment, name='like_comment'),
]

urlpatterns = [
    path('feed/', views.feed, name='feed'),
    path('users/', include(user_urlpatterns)),
    path('auth/', include(auth_urlpatterns)),
    path('posts/', include(post_urlpatterns)),
    path('comments/', include(comment_urlpatterns)),
    path('social/signup/', views.signup_redirect, name='signup_redirect'),
]

feed/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField

POST_IMAGE_PATH = 'post/images'
PROFILE_IMAGES_PATH = 'user/images'
DEFAULT_PROFILE_IMAGE_PATH = 'user/images/default_user.png'


class User(AbstractUser):
    """User model. Standard User model supplemented with fields bio and
    profile image."""
    bio = models.TextField(blank=True)
    profile_image = CloudinaryField(
        'profile_image',
        folder=PROFILE_IMAGES_PATH,
        default=DEFAULT_PROFILE_IMAGE_PATH)
    followers = models.ManyToManyField('self', related_name='following',
                                       symmetrical=False,
                                       blank=True)

    def __str__(self):
        return self.username


class Post(models.Model):
    """Post model. Contains description, owner(user who created post),
    likes(list of users who liked this post), tags and posted(date and
    time when it were posted) fields."""
    description = models.TextField(max_length=400,
                                   help_text='Write a description',
                                   blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE,
                              related_name='owner')
    likes = models.ManyToManyField(User, related_name='liked_posts',
                                   blank=True)
    tags = TaggableManager(blank=True)
    posted = models.DateTimeField(auto_now_add=True)


class Image(models.Model):
    """Image model. Relates to Post model. Representation of posts images."""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = CloudinaryField('post_image', folder=POST_IMAGE_PATH)


class Comment(models.Model):
    """Comment model. Relates to Post and User model.
    Representation of comments for posts."""
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    text = models.TextField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE,
                              related_name='comments')
    likes = models.ManyToManyField(User, related_name='liked_comments',
                                   blank=True)
    posted = models.DateTimeField(auto_now_add=True)

feed/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from taggit.forms import TagField

from .models import Post


class SignUpForm(UserCreationForm):
    """Sign up form. Email field added to standard UserCreationForm."""
    email = forms.EmailField(help_text='A valid email address, please.',
                             required=True)

    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'email']


class EditProfile(forms.ModelForm):
    """Form for profile editing."""
    class Meta:
        model = get_user_model()
        fields = ['profile_image', 'username', 'first_name',
                  'last_name', 'email', 'bio']


class CreatePostForm(forms.ModelForm):
    """Form for post creating."""
    tags = TagField(help_text='Tags with commas.')

    class Meta:
        model = Post
        fields = ['description', 'tags']

feed/views.py
import pytz

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db import IntegrityError
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.core.exceptions import ObjectDoesNotExist

from .forms import SignUpForm, EditProfile, CreatePostForm
from .models import User, Post, Image, Comment
from .tokens import account_activation_token


def activate_email(request, user, email):
    """Send an email with account confirmation link.
    :param request:
    :param user:
    :param email:
    :return:
    """
    mail_subject = "Activate your account."
    message = render_to_string("template_activate_account.html", {
        'user': user,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[email])
    email.send()


def signup_user(request):
    """Sign up user and send a confirmation email.
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'feed/signup_user.html',
                      {'form': SignUpForm()})
    # Create a new user
    if request.POST['password1'] == request.POST['password2']:
        try:
            user = User.objects.create_user(
                request.POST['username'],
                email=request.POST['email'],
                password=request.POST['password1'])
            user.is_active = False
            user.save()
            activate_email(request, user, request.POST['email'])
            messages.success(request,
                             "You have been registered successfully."
                             "Please confirm your email before login.")
            return redirect('feed:login')
        except IntegrityError:
            messages.error(request,
                           f"That username has already been taken. "
                           "Please choose a new username.")
            return render(request, 'feed/signup_user.html', {
                'form': SignUpForm()
            })
    messages.error(request, "Passwords did not match!")
    return render(request, 'feed/signup_user.html', {
        'form': SignUpForm()
    })


def signup_redirect(request):
    messages.error(request, "That email has already been registered.")
    return redirect('feed:login')


def activate_user(request, uidb64, token):
    """Activate user by uid64 and token in link.
    :param request:
    :param uidb64:
    :param token:
    :return:
    """
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except ObjectDoesNotExist:
        user = None

    if user and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)

        return redirect('feed:user_edit_profile', user.id)


def login_user(request):
    """Login user page.
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'feed/login.html',
                      {'form': AuthenticationForm()})

    user = authenticate(request, username=request.POST['username'],
                        password=request.POST['password'])

    if user is None:
        messages.error(request, 'Username and password did not match.')
        return render(request, 'feed/login.html', {
            'form': AuthenticationForm()
        })

    if not user.is_active:
        messages.error(request, "Looks like your account isn't active."
                       "Please check your mailbox and confirm your"
                       "email to activate your account.")
        return render(request, 'feed/login.html', {
            'form': AuthenticationForm()
        })

    messages.success(request, f"Successfully logged in as {user.username}.")
    login(request, user)
    return redirect('feed:feed')


@login_required
def logout_user(request):
    """Log out user functionality.
    :param request:
    :return:
    """
    if request.method == 'POST':
        logout(request)
        messages.success(request, 'Successfully logged out.')
        return redirect('feed:login')


@login_required
def user_profile(request, user_id):
    """Representation of user's profile page.
    :param request:
    :param user_id:
    :return:
    """
    user = get_object_or_404(User, pk=user_id)
    followed = False
    if request.user in user.followers.all():
        followed = True
    return render(request, 'feed/user_profile.html', {
        'user': user,
        'followed': followed,
    })


@login_required
def user_edit_profile(request, user_id):
    """Representation of user's editing profile page.
    :param request:
    :param user_id:
    :return:
    """
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'GET':
        if user != request.user:
            return redirect('feed:user_profile', user_id)
        form = EditProfile(instance=user)
        return render(request, 'feed/user_edit_profile.html', {
            'form': form,
        })
    form = EditProfile(request.POST, request.FILES, instance=user)
    form.save()
    return redirect('feed:user_profile', user.id)


@login_required
def feed(request):
    """Representation of feed page. There user can see all posts.
    :param request:
    :return:
    """
    posts = Post.objects.order_by('-posted')[:25]
    following_users = [following for following
                       in request.user.following.all()]
    following_posts = Post.objects.filter(owner__in=following_users).order_by(
        '-posted')[:25]
    return render(request, 'feed/feed.html', {
        'posts': posts,
        'following_posts': following_posts,
    })


@login_required
def create_post(request):
    """Create post page. There user can create new post.
    :param request:
    :return:
    """
    if request.method == 'POST':
        post = Post.objects.create(description=request.POST['description'],
                                   owner=request.user)
        tags = request.POST['tags'].replace(' ', '').split(',')
        post.tags.add(*tags)
        post.save()
        for image in request.FILES.getlist('images'):
            Image.objects.create(post=post, image=image)
        return redirect('feed:feed')
    return render(request, 'feed/create_post.html', {
        'form': CreatePostForm(),
    })


@login_required
def like(request, post_id):
    """Functionality for liking posts. User can like post and
    unlike as well.
    :param request:
    :param post_id: the ID of the post to be liked.
    :return:
    """
    post = get_object_or_404(Post, pk=post_id)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
        return JsonResponse({'likes_count': post.likes.count(), 'liked': False})
    post.likes.add(request.user)
    return JsonResponse({'likes_count': post.likes.count(), 'liked': True})


@login_required
def follow(request, user_id):
    """Functionality for following users. User can follow and
    unfollow other user.
    :param request:
    :param user_id:
    :return:
    """
    user = get_object_or_404(User, pk=user_id)
    if request.user in user.followers.all():
        user.followers.remove(request.user)
        return JsonResponse({'followers': user.followers.count(), 'followed': False})
    user.followers.add(request.user)
    return JsonResponse({'followers': user.followers.count(), 'followed': True})


@login_required
def followers(request, user_id):
    """Representation of page with list of followers.
    :param request:
    :param user_id:
    :return:
    """
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'feed/followers.html', {
        'user': user,
    })


@login_required
def following(request, user_id):
    """Representation of page with list of following.
    :param request:
    :param user_id:
    :return:
    """
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'feed/following.html', {
        'user': user,
    })


@login_required
def make_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    Comment.objects.create(text=request.POST['feed-comment'],
                           owner=request.user,
                           post=post)
    comments = {'post_id': post_id, 'comments': [{
        'owner': comment.owner.username, 'text': comment.text,
        'posted': comment.posted.astimezone(pytz.timezone(
            'Europe/Kiev')).strftime('%d.%m.%y %H:%M'),
        'id': comment.id,
        'liked': request.user in comment.likes.all(),
        'likes_count': comment.likes.count()
    } for comment in post.comments.order_by('posted')]}
    return JsonResponse(comments, safe=False)


@login_required
def like_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
        return JsonResponse({'likes_count': comment.likes.count(),
                             'liked': False})
    comment.likes.add(request.user)
    return JsonResponse({'likes_count': comment.likes.count(),
                         'liked': True})

feed/templates/feed/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% block head %}{% endblock %}
    <link href="{% static 'feed/styles.css' %}" rel="stylesheet">
    <link href="{% static 'feed/base.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - DjangoGramm</title>
</head>
<body>
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a href="{% url 'feed:feed' %}" class="navbar-brand">DJANGO-GRAMM</a>
      <div class="float-sm-end">
        {% if request.user.is_authenticated %}

          <form method="post" action="{% url 'feed:logout' %}" class="float-sm-end m-1">
              {% csrf_token %}
              <button class="btn btn-outline-success" type="submit">LogOut</button>
          </form>

          <form action="{% url 'feed:user_profile' request.user.id %}" class="float-sm-end m-1">
              <button class="btn btn-outline-success" type="submit">
              <img class="rounded-circle" src="{{ request.user.profile_image.url }}" width="23px">
              {{ request.user.username }}</button>
          </form>

          <form action="{% url 'feed:create_post' %}" class="float-sm-end m-1">
              <button class="btn btn-outline-success" type="submit">Create Post</button>
          </form>

        {% else %}

        <form action="{% url 'feed:signup' %}" class="float-sm-end m-1">
          <button class="btn btn-outline-success" type="submit">Sign Up</button>
        </form>
        <form action="{% url 'feed:login' %}" class="float-sm-end m-1">
          <button class="btn btn-outline-success" type="submit">Log In</button>
        </form>

        {% endif %}

      </div>
  </div>
</nav>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="{% static 'feed/bundle.js' %}"></script>
<script src="{% static 'feed/base.js' %}"></script>
{% include 'feed/messaging.html' %}
{% block content %}{% endblock %}
</body>
</html>

feed/templates/feed/create_post.html
{% extends 'feed/base.html' %}
{% load static %}
{% block title %}Create post{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'feed/create_post.css' %}">
{% endblock %}

{% block content %}
<form style="width: 600px;" class="mx-sm-auto" method="post" enctype="multipart/form-data">
    <h1>Create post</h1>
    {% csrf_token %}
    <label for="formFileMultiple" class="form-label">Input images.</label>
    <input name="images" class="form-control" type="file" id="formFileMultiple" multiple>
    <br>
    {{ form.as_p }}
    <input type="submit" value="Create post">
</form>
{% endblock %}

feed/templates/feed/feed.html
{% extends 'feed/base.html' %}
{% load static %}

{% block title %}Feed{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'feed/feed.css' %}">
{% endblock %}

{% block content %}

<ul class="nav nav-tabs feed" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active link-secondary" id="feed-tab" data-bs-toggle="tab"
            data-bs-target="#feed-tab-pane" type="button" role="tab"
            aria-controls="feed-tab-pane" aria-selected="true">feed</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link link-secondary" id="following-tab" data-bs-toggle="tab"
            data-bs-target="#following-tab-pane" type="button" role="tab"
            aria-controls="following-tab-pane" aria-selected="false">following</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="feed-tab-pane" role="tabpanel" aria-labelledby="feed-tab" tabindex="0">
      {% for post in posts %}
        <div id="feed{{ post.id }}" class="card feed post" style="max-width: 600px;">
          <div class="card-body">
            <a class="d-sm-flex link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
               href="{% url 'feed:user_profile' post.owner.id %}">
            <img class="rounded-circle" src="{{ post.owner.profile_image.url }}" width="40px">
            <h5 class="card-title m-sm-1">{{ post.owner }}</h5>
            </a>
          </div>
          <div id="carousel{{ post.id }}" class="carousel slide">
                <div class="carousel-inner">
                    {% for image in post.image_set.all %}
                    <div class="carousel-item active">
                        <img src="{{ image.image.url }}" class="d-block" style="max-width: 600px;">
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button"
                        data-bs-target="#carousel{{ post.id }}" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button"
                        data-bs-target="#carousel{{ post.id }}" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
          </div>
          <div class="card-body">
              <span class="badge text-bg-secondary likes_count{{ post.id }}">{{ post.likes.count }}</span>
              <a onclick="like({{ post.id }})"
                 class="btn btn-outline-secondary">
                <img class="liked-post{{ post.id }}"
                  {% if request.user in post.likes.all %}
                  src="{% static 'feed/liked.png' %}"
                  {% else %}
                  src="{% static 'feed/doesnt_liked.png' %}"
                  {% endif %}
                width="25px">
              </a>
              <p class="card-text">{{ post.description }}</p>
              {% for tag in post.tags.all %}
              <span class="badge bg-secondary">#{{ tag }}</span>
              {% endfor %}
          </div>
            <div class="card-footer">
              <ul class="list-group comments">
                <div class="comments{{ post.id }}">
                  {% for comment in post.comments.all|dictsort:'posted' %}
                    <li class="list-group-item comment">
                      <span class="comment-text"><b>{{ comment.owner.username }}</b> {{ comment.text }}</span>
                      <span class="comment-posted">{{ comment.posted|date:"d.m.y H:i" }}</span>
                      <span class="comment-like">
                        <span class="comment-likes-count comment-likes-count{{ comment.id }}">{{ comment.likes.count }}</span>
                        <a onclick="likeComment({{ comment.id }})">
                          <img class="comment-like-btn comment-like-btn{{ comment.id }}"
                               {% if request.user in comment.likes.all %}
                               src="{% static 'feed/liked.png' %}"
                               {% else %}
                               src="{% static 'feed/doesnt_liked.png' %}"
                               {% endif %}
                               width="18px">
                        </a>
                      </span>
                    </li>
                  {% endfor %}
                </div>
                <form method="POST" action="{% url 'feed:make_comment' post.id %}" class="send-comment list-group-item comment-input">
                  <div class="input-group">
                    {% csrf_token %}
                    <input type="text" name="feed-comment" class="form-control input-comment{{ post.id }}" placeholder="Your comment..." aria-label="Your comment..." aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="submit">Send</button>
                  </div>
                </form>
              </ul>
            </div>
        </div>
        <br>
      {% endfor %}
  </div>
  <div class="tab-pane fade" id="following-tab-pane" role="tabpanel" aria-labelledby="following-tab" tabindex="0">
      {% for post in following_posts %}
        <div id="post{{ post.id }}" class="card feed post" style="max-width: 600px;">
          <div class="card-body">
            <a class="d-sm-flex link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
               href="{% url 'feed:user_profile' post.owner.id %}">
            <img class="rounded-circle" src="{{ post.owner.profile_image.url }}" width="40px">
            <h5 class="card-title m-sm-1">{{ post.owner }}</h5>
            </a>
          </div>
          <div id="following_carousel{{ post.id }}" class="carousel slide">
                <div class="carousel-inner">
                    {% for image in post.image_set.all %}
                    <div class="carousel-item active">
                        <img src="{{ image.image.url }}" class="d-block" style="max-width: 600px;">
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button"
                        data-bs-target="#following_carousel{{ post.id }}" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button"
                        data-bs-target="#following_carousel{{ post.id }}" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
          </div>
          <div class="card-body">
              <span class="badge text-bg-secondary likes_count{{ post.id }}">{{ post.likes.count }}</span>
              <a onclick="like({{ post.id }})"
                class="btn btn-outline-secondary">
                <img class="liked-post{{ post.id }}"
                  {% if request.user in post.likes.all %}
                  src="{% static 'feed/liked.png' %}"
                  {% else %}
                  src="{% static 'feed/doesnt_liked.png' %}"
                  {% endif %}
                width="25px">
              </a>
              <p class="card-text">{{ post.description }}</p>
              {% for tag in post.tags.all %}
              <span class="badge bg-secondary">#{{ tag }}</span>
              {% endfor %}

          </div>
            <div class="card-footer">
              <ul class="list-group comments">
                <div class="comments{{ post.id }}">
                  {% for comment in post.comments.all|dictsort:'posted' %}
                    <li class="list-group-item comment">
                      <span class="comment-text"><b>{{ comment.owner.username }}</b> {{ comment.text }}</span>
                      <span class="comment-posted">{{ comment.posted|date:"d.m.y H:i" }}</span>
                      <span class="comment-like">
                        <span class="comment-likes-count comment-likes-count{{ comment.id }}">{{ comment.likes.count }}</span>
                        <a onclick="likeComment({{ comment.id }})">
                          <img class="comment-like-btn comment-like-btn{{ comment.id }}"
                               {% if request.user in comment.likes.all %}
                               src="{% static 'feed/liked.png' %}"
                               {% else %}
                               src="{% static 'feed/doesnt_liked.png' %}"
                               {% endif %}
                               width="18px">
                        </a>
                      </span>
                    </li>
                  {% endfor %}
                </div>
                <form method="POST" action="{% url 'feed:make_comment' post.id %}" class="send-comment list-group-item comment-input">
                  <div class="input-group">
                    {% csrf_token %}
                    <input type="text" name="feed-comment" class="form-control input-comment{{ post.id }}" placeholder="Your comment..." aria-label="Your comment..." aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="submit">Send</button>
                  </div>
                </form>
              </ul>
            </div>
        </div>
        <br>
        {% endfor %}
  </div>
</div>

<script src="{% static 'feed/feed.js' %}"></script>

{% endblock %}

feed/templates/feed/followers.html
{% extends 'feed/base.html' %}
{% load static %}

{% block title %}Followers - {{ user.username }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'feed/followers.css' %}">
{% endblock %}

{% block content %}

<div class="main">

    <h3>
        Followers
    </h3>

    <ul class="list-group">
        {% for follower in user.followers.all %}
        <li class="list-group-item d-lg-inline">
            <a class="link-secondary link-offset-2 link-underline link-underline-opacity-0"
               href="{% url 'feed:user_profile' follower.id %}">
                <img class="rounded-circle" style="width: 30px;" src="{{ follower.profile_image.url }}">
                <h5 class="d-lg-inline">{{ follower }}</h5>
            </a>
        </li>
        {% endfor %}
    </ul>

</div>

{% endblock %}

feed/templates/feed/following.html
{% extends 'feed/base.html' %}
{% load static %}

{% block title %}Following - {{ user.username }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'feed/followers.css' %}">
{% endblock %}

{% block content %}

<div class="main">

    <h3>
        Following
    </h3>

    <ul class="list-group">
        {% for following in user.following.all %}
        <li class="list-group-item d-lg-inline">
            <a class="link-secondary link-offset-2 link-underline link-underline-opacity-0"
               href="{% url 'feed:user_profile' following.id %}">
                <img class="rounded-circle" style="width: 30px;" src="{{ following.profile_image.url }}">
                <h5 class="d-lg-inline">{{ following }}</h5>
            </a>
        </li>
        {% endfor %}
    </ul>

</div>

{% endblock %}

feed/templates/feed/signup_user.html
{% extends 'feed/base.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'feed/signup.css' %}">
{% endblock %}

{% block content %}
<div class="signup">
<h1>Sign Up</h1>

<h2>{{ message }}</h2>

<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Sign Up</button>
</form>
</div>
{% endblock %}

feed/templates/feed/user_profile.html
{% extends 'feed/base.html' %}
{% load static %}

{% block title %}{{ user.username }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'feed/user_profile.css' %}">
{% endblock %}

{% block content %}
<div class="profile">
    <div class="username">
        <span>{{ user.username }}</span>
    </div>
    <img class="profile_image" src="{{ user.profile_image.url }}">
    <div class="follow">
        {% if user == request.user %}<span class="edit d-md-flex"><a href="{% url 'feed:user_edit_profile' user.id %}">Edit</a></span><br>{% endif %}
        <div class="container px-4 text-center">
          <div class="row gx-5">
            <div class="col">
             <a class="link-secondary link-offset-2 link-underline link-underline-opacity-0"
                href="{% url 'feed:followers' user.id %}">
                 <div class="p-2">
                     <span id="followers_count">{{ user.followers.count }}</span>
                     <br>
                     <span>followers</span>
                 </div>
             </a>
            </div>
            <div class="col">
              <a class="link-secondary link-offset-2 link-underline link-underline-opacity-0"
                 href="{% url 'feed:following' user.id %}">
                  <div class="p-2">
                      <span>{{ user.following.count }}</span>
                      <br>
                      <span>following</span>
                  </div>
              </a>
            </div>
          </div>
        </div>
        <br>
        {% if user != request.user %}
        <div class="d-md-flex"><a class="mx-sm-auto btn btn-outline-secondary"
                                  onclick="follow({{ user.id }})"
                                  id="follow">
            {% if not followed %}
            Follow
            {% else %}
            Unfollow
            {% endif %}
        </a></div><br>
        {% endif %}
    </div>
    <div class="user_info">
        <span class="full_name">Full name: {{ user.first_name }} {{ user.last_name }}</span><br><br>
        <span class="bio">Bio: {{ user.bio }}</span>
    </div>
</div>

<script>

    function follow(user_id) {
      $.ajax({
        type: 'GET',
        url: window.location.origin + '/user/' + user_id + '/follow',
        success: function(response) {
          $('#followers_count').text(response.followers);
          $('#follow').text('Follow');
          if (response.followed) {
            $('#follow').text('Unfollow');
          };
        }
      })
    }

</script>

{% endblock %}